name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@70f8dfc6d54fdcfc58940cd93cecced306374ed7 # main
        with:
          repository: openstack/senlin
          ref: 201847fa418137e61b7061adc4d0e964197cf65f # unmaintained/zed

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@70f8dfc6d54fdcfc58940cd93cecced306374ed7 # main
        with:
          image-name: senlin
          build-contexts: senlin=openstack/senlin
          push: ${{ github.event_name != 'pull_request' }}
